services:
  ttt:
      image: ghcr.io/jquagga/ttt:main 
      container_name: ttt
      init: true
      hostname: ttt
      restart: unless-stopped
      volumes:
        - /srv/nfs/media/transcribe:/app/media/transcribe
        - ./destinations.csv:/app/destinations.csv:ro
        - ./models:/app/models
        - ./cache:/home/mambauser/.cache/torch/kernels 
        #- /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      user: "1000"
      environment:
        - TTT_FASTERWHISPER_VAD_FILTER=True
        - TTT_FASTERWHISPER_LANGUAGE=en
        - TTT_ATTACH_AUDIO=True
        - TTT_FASTERWHISPER_HOTWORDS=Prince William Bravo Sudley
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
