services:
  ttt:
      image: ghcr.io/jquagga/ttt:main
      container_name: ttt
      hostname: ttt
      restart: unless-stopped
      volumes:
        - ./media/transcribe:/app/media/transcribe
        - ./destinations.csv:/app/destinations.csv:ro
        - ./models:/app/models #faster_whisper models
      user: "1000"
      environment:
        - TZ=America/New_York
        - TTT_WHISPERCPP_URL=${TTT_WHISPERCPP_URL}
        - TTT_DEEPGRAM_KEY=${TTT_DEEPGRAM_KEY}
