services:
  ttt:
      image: ghcr.io/jquagga/ttt:main 
      container_name: ttt
      hostname: ttt
      restart: unless-stopped
      volumes:
        - ./media/transcribe:/app/media/transcribe
        - ./destinations.csv:/app/destinations.csv:ro
        - ./models:/app/models
        #- /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      user: "1000"
      environment:
        #- TTT_WHISPERCPP_URL=${TTT_WHISPERCPP_URL}
        - HF_HOME=models
