name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ffmpeg
  - gcc
  - pip
  - pip:
    - --index-url https://download.pytorch.org/whl/cpu
    - torch
    - torchvision
    - torchaudio
  - pip:
    - better_profanity
    - transformers
    - accelerate
    - apprise