name: base
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - git
  - python=3.12
  - apprise
  - pip
  - pip:
    - scrubadub
  - transformers
  - accelerate
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=12.1