name: base
channels:
  - conda-forge
dependencies:
  - python=3.13
  - ffmpeg
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
  - pip:
      - better_profanity
      - transformers
      - accelerate
      - apprise
